default:
  image: maven:3.6.3-openjdk-11-jacoco-0.8.6
  

stages:
  - build
  - test
#  - deploy

validateAndCompile:
  stage: build
  script: mvn clean compile

runUnitTests:
  stage: test
  script: mvn test