default:
  image: maven:3.6.3-openjdk-11

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
stages:
  - build
  - test
#  - deploy

cache:
  paths:
    - .m2/repository

validateAndCompile:
  stage: build

  script: mvn $MAVEN_OPTS clean compile > mvncompileoutput.txt

  artifacts:
    expire_in: 10 mins
    paths:
      - mvncompileoutput.txt

runUnitTests:
  stage: test
  script: mvn $MAVEN_OPTS test
