default:
  image: maven:jdkjacoco
  
stages:
  - build
  - test
#  - deploy

cache:
  paths:
    - cache

validateAndCompile:
  stage: build
  before_script:
    - rm -rf ~/.m2/repository
    - mv cache ~/.m2/repository

  script: mvn clean compile

  after_script:
    - rm -rf cache
    - cp ~/.m2/repository cache

runUnitTests:
  stage: test
  before_script:
    - rm -rf ~/.m2/repository
    - mv cache ~/.m2/repository

  script: mvn test
  after_script:
    - rm -rf cache
    - cp ~/.m2/repository cache
