default:
  image: maven:jdkjacoco
  
stages:
  - build
  - test
#  - deploy

cache:
  paths:
    - cache

validateAndCompile:
  stage: build
  before_script:
    - rm -rf ~/.m2/repository || true
    - mv cache ~/.m2/repository || true

  script: mvn clean compile

  after_script:
    - rm -rf cache || true
    - cp -r ~/.m2/repository cache || true

runUnitTests:
  stage: test
  before_script:
    - rm -rf ~/.m2/repository || true
    - mv cache ~/.m2/repository || true

  script: mvn test
  after_script:
    - rm -rf cache || true
    - cp -r ~/.m2/repository cache || true
