default:
  image: maven:jdkjacoco
  
stages:
  - build
  - test
#  - deploy

cache:
  paths:
    - /root/.m2/repository


validateAndCompile:
  stage: build
  script: mvn clean compile

runUnitTests:
  stage: test
  script: mvn test